// AgentFS FFI - C-compatible interface for FSKit Swift extension
// Auto-generated by cbindgen - do not edit manually


#ifndef AGENTFS_FFI_H
#define AGENTFS_FFI_H

/* Warning: this file was auto-generated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque handle to a mounted filesystem instance.
//
// This handle wraps the Rust FileSystem trait object and a Tokio runtime
// for executing async operations.
typedef struct AgentFSHandle AgentFSHandle;

// Result type for FFI operations.
//
// - `success`: true if the operation succeeded
// - `error_code`: 0 on success, positive errno value on failure
typedef struct FFIResult {
    bool success;
    int32_t error_code;
} FFIResult;

// File statistics returned to Swift.
//
// Mirrors the Rust `Stats` struct with C-compatible types.
typedef struct FFIStats {
    int64_t ino;
    uint32_t mode;
    uint32_t nlink;
    uint32_t uid;
    uint32_t gid;
    int64_t size;
    int64_t atime;
    int64_t mtime;
    int64_t ctime;
} FFIStats;

// Buffer for returning variable-length data.
//
// The caller is responsible for freeing this buffer using `agentfs_free_buffer`.
typedef struct FFIBuffer {
    uint8_t *data;
    size_t len;
    size_t capacity;
} FFIBuffer;

// Filesystem statistics for statfs.
typedef struct FFIFilesystemStats {
    uint64_t inodes;
    uint64_t bytes_used;
} FFIFilesystemStats;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Open an AgentFS database and return a handle.
//
// # Arguments
// * `db_path` - Path to the SQLite database file (null-terminated C string)
//
// # Returns
// * Non-null handle on success
// * Null pointer on failure
//
// # Safety
// `db_path` must be a valid null-terminated C string.
struct AgentFSHandle *agentfs_open(const char *db_path);

// Close and free an AgentFS handle.
//
// # Safety
// `handle` must be a valid handle returned by `agentfs_open`, or null.
// After calling this function, the handle must not be used again.
void agentfs_close(struct AgentFSHandle *handle);

// Get file statistics, following symlinks.
//
// # Safety
// - `handle` must be a valid handle
// - `path` must be a valid null-terminated C string
// - `out_stats` must be a valid pointer to write stats
struct FFIResult agentfs_stat(const struct AgentFSHandle *handle,
                              const char *path,
                              struct FFIStats *out_stats);

// Get file statistics without following symlinks.
//
// # Safety
// Same as `agentfs_stat`.
struct FFIResult agentfs_lstat(const struct AgentFSHandle *handle,
                               const char *path,
                               struct FFIStats *out_stats);

// Read data from a file at offset.
//
// # Arguments
// * `handle` - AgentFS handle
// * `path` - File path
// * `offset` - Byte offset to start reading
// * `size` - Maximum bytes to read
// * `out_buffer` - Output buffer (caller must free with `agentfs_free_buffer`)
//
// # Safety
// - All pointers must be valid
// - `out_buffer` will be filled with allocated data that must be freed
struct FFIResult agentfs_pread(const struct AgentFSHandle *handle,
                               const char *path,
                               uint64_t offset,
                               uint64_t size,
                               struct FFIBuffer *out_buffer);

// Write data to a file at offset.
//
// Creates the file if it doesn't exist. Extends the file if writing past end.
//
// # Safety
// - All pointers must be valid
// - `data` must point to at least `data_len` bytes
struct FFIResult agentfs_pwrite(const struct AgentFSHandle *handle,
                                const char *path,
                                uint64_t offset,
                                const uint8_t *data,
                                size_t data_len);

// Read entire file contents.
//
// # Safety
// Same as `agentfs_pread`.
struct FFIResult agentfs_read_file(const struct AgentFSHandle *handle,
                                   const char *path,
                                   struct FFIBuffer *out_buffer);

// Write entire file contents (creates or overwrites).
//
// # Safety
// Same as `agentfs_pwrite`.
struct FFIResult agentfs_write_file(const struct AgentFSHandle *handle,
                                    const char *path,
                                    const uint8_t *data,
                                    size_t data_len);

// Truncate a file to a specific size.
//
// # Safety
// - `handle` must be valid
// - `path` must be a valid null-terminated string
struct FFIResult agentfs_truncate(const struct AgentFSHandle *handle,
                                  const char *path,
                                  uint64_t size);

// Read directory entries.
//
// Returns entries as a JSON array string: `["file1", "file2", "dir1"]`
//
// # Safety
// - `out_entries` will be set to a newly allocated string (free with `agentfs_free_string`)
struct FFIResult agentfs_readdir(const struct AgentFSHandle *handle,
                                 const char *path,
                                 char **out_entries);

// Create a directory.
//
// # Safety
// Standard pointer validity requirements.
struct FFIResult agentfs_mkdir(const struct AgentFSHandle *handle, const char *path);

// Remove a file or empty directory.
//
// # Safety
// Standard pointer validity requirements.
struct FFIResult agentfs_remove(const struct AgentFSHandle *handle, const char *path);

// Rename/move a file or directory.
//
// # Safety
// Standard pointer validity requirements.
struct FFIResult agentfs_rename(const struct AgentFSHandle *handle,
                                const char *from,
                                const char *to);

// Create a symbolic link.
//
// # Arguments
// * `target` - What the symlink points to
// * `linkpath` - Path where the symlink will be created
//
// # Safety
// Standard pointer validity requirements.
struct FFIResult agentfs_symlink(const struct AgentFSHandle *handle,
                                 const char *target,
                                 const char *linkpath);

// Read the target of a symbolic link.
//
// # Safety
// - `out_target` will be set to a newly allocated string (free with `agentfs_free_string`)
struct FFIResult agentfs_readlink(const struct AgentFSHandle *handle,
                                  const char *path,
                                  char **out_target);

// Get filesystem statistics.
//
// # Safety
// Standard pointer validity requirements.
struct FFIResult agentfs_statfs(const struct AgentFSHandle *handle,
                                struct FFIFilesystemStats *out_stats);

// Synchronize file data to persistent storage.
//
// # Safety
// Standard pointer validity requirements.
struct FFIResult agentfs_fsync(const struct AgentFSHandle *handle, const char *path);

// Free a string allocated by Rust.
//
// # Safety
// `s` must be a string returned by an agentfs_* function, or null.
void agentfs_free_string(char *s);

// Free a buffer allocated by Rust.
//
// # Safety
// `buf` must be a buffer returned by an agentfs_* function.
void agentfs_free_buffer(struct FFIBuffer buf);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AGENTFS_FFI_H */
